### PR TITLE
Revert "Added "uhfHeaderId": "MSDocsHeader-VisualStudio","

### PR DESCRIPTION
**Pull request by nokura**
Reverts MicrosoftDocs/visualstudio-docs.it-it#3

### CODE REVIEW

**Comment by v-maudel** [comment]
Hello, @nokura , 

Thank for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly. 
 
Thanks for your time and support on this.

Kind regards,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
@nokura Should we merge this PR?

**Comment by gosali** [comment]
@nokura Should we merge this PR?

**Comment by gosali** [comment]
@nokura Should we merge this PR?

**Pull request closed without merging**
